spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&failOverReadOnly=false
    username: root
    password: root

# 日志配置
logging:
  level:
    com.yxt: debug
    org.mybatis: debug
    org.springframework: warn

image:
  upload:
    path: D:\\works\\projects\\hbuilderx\\gg815\\gg_admin\\target\\classes\\static\\upload\\
  url:
    prefix: http://192.168.56.1:8108/upload/