server:
  port: 7111
spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: yyd-system    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          predicates:
            - Path= /system/**  #断言,路径相匹配的进行路由
          uri: lb://yyd-system  # 微服务名称
          filters:
            - StripPrefix=1
        - id: yyd-demo
          predicates:
            - Path= /demo/**
          uri: lb://yyd-demo
          filters:
            - StripPrefix=1
        - id: yyd-file
          predicates:
            - Path= /files/**
          uri: lb://yyd-file
          filters:
            - StripPrefix=1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 300000
#自定义白名单
ignore:
  whites:
    - /files/v1/file/upload  #上传文件



  whitesTwo:
    ###swagger相关开始
    - /doc.html
    - /webjars/**
    - /swagger-resources
    - /v2/**
    - /favicon.ico
    - /upload/**
    - /mode-Text.js
    ###swagger相关结束

