server:
  port: 7111
spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: yyd-system
          predicates:
            - Path= /system/**
          uri: lb://yyd-system
          filters:
            - StripPrefix=1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 300000

ignore:
  whites:
    - /system/file/upload  #上传文件



  whitesTwo:
    ###swagger相关开始
    - /doc.html
    - /webjars/**
    - /swagger-resources
    - /v2/**
    - /favicon.ico
    - /upload/**
    - /mode-Text.js
    ###swagger相关结束

